site_name: TP Alpine Linux
site_description: Documentation du TP Alpine Linux
site_url: https://ornech.github.io/TP-AlpineLinux/

docs_dir: site_docs
site_dir: site
repo_url: https://github.com/ornech/TP-AlpineLinux
edit_uri: edit/master/site_docs/


theme:
  name: mkdocs
  theme: flatly
  locale: fr

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - fenced_code
  - codehilite
  - tables
  - footnotes
  - def_list

extra_css:
  - styles.css
